def(craves(Car,City)):-pleasure(Car), food(City).
def(craves(Cargo,City)):-pain(Cargo), food(City).
def(fears(Cargo, Car)):-pain(Cargo), pleasure(Car).
def(locale(City, Fuel)):-food(City),province(Fuel).
def(harmony(Car, V)):-pleasure(Car), planet(V).


food(lettuce).
food(marzipan).
food(wonderbread).
food(onion).
food(bacon).
food(popover).
food(ham).
food(guava).
food(chicken).
food(cantelope).
food(pepper).
food(scallop).
food(beef).
food(wurst).
food(lamb).
food(pea).
food(cherry).
food(shrimp).
food(hamburger).
food(kale).
food(muffin).
pleasure(stimulation).
pleasure(curiosity).
pleasure(triumph).
pleasure(understanding).
pleasure(expectation).
pleasure(entertainment).
pleasure(intoxication).
pleasure(satisfaction).
pleasure(aesthetics).
pleasure(achievement).
pleasure(love).
pleasure(lubricity).
pleasure(rest).
pleasure(learning).
pleasure(excitement).
pleasure(satiety).
pain(angina).
pain(grief).
pain(prostatitis).
pain(jealousy).
pain(dread).
pain(boils).
pain(hangover).
pain(anger).
pain(depression).
pain(loneliness).
pain(abrasion).
pain(sciatica).
pain(laceration).
pain(anxiety).
pain(dread_2).
pain(sciatica_1).
pain(hangover_4).
pain(abrasion_3).
province(surrey).
province(alsace).
province(kentucky).
province(goias).
province(moravia).
province(oregon).
planet(uranus).
planet(neptune).
planet(jupiter).
planet(mercury).
eats(wurst,pea).
orbits(neptune,jupiter).
eats(beef,shrimp).
eats(hamburger,cherry).
eats(guava,ham).
attacks(moravia,oregon).
attacks(kentucky,goias).
eats(muffin,pea).
eats(marzipan,wonderbread).
eats(beef,cherry).
eats(pea,lamb).
eats(lamb,shrimp).
eats(scallop,beef).
eats(scallop,cantelope).
eats(cherry,scallop).
eats(lamb,cantelope).
eats(ham,guava).
eats(guava,chicken).
eats(onion,bacon).
eats(marzipan,lettuce).
orbits(jupiter,mercury).
eats(wonderbread,lettuce).
eats(cherry,beef).
eats(lamb,pepper).
eats(popover,bacon).
eats(bacon,onion).
eats(cherry,hamburger).
eats(pepper,wurst).
attacks(goias,moravia).
eats(shrimp,muffin).
eats(shrimp,lamb).
eats(pea,muffin).
eats(hamburger,kale).
eats(kale,wurst).
eats(beef,scallop).
eats(bacon,marzipan).
eats(kale,scallop).
orbits(uranus,neptune).
eats(pea,wurst).
eats(pepper,lamb).
eats(wonderbread,marzipan).
eats(lettuce,marzipan).
eats(popover,ham).
eats(scallop,hamburger).
eats(scallop,shrimp).
eats(kale,pepper).
eats(chicken,popover).
eats(lamb,pea).
eats(shrimp,beef).
eats(hamburger,scallop).
eats(scallop,kale).
eats(pepper,kale).
eats(ham,popover).
eats(lettuce,wonderbread).
eats(wurst,kale).
eats(wurst,pepper).
eats(marzipan,bacon).
eats(cantelope,scallop).
eats(muffin,shrimp).
eats(chicken,cherry).
eats(onion,lettuce).
eats(chicken,guava).
attacks(surrey,alsace).
eats(cantelope,lamb).
eats(bacon,popover).
eats(lettuce,onion).
eats(scallop,cherry).
eats(popover,chicken).
attacks(alsace,kentucky).
eats(kale,hamburger).
eats(shrimp,scallop).
eats(cherry,chicken).


initial([
harmony(satisfaction,neptune),
craves(entertainment,chicken),
harmony(excitement,neptune),
harmony(curiosity,jupiter),
harmony(triumph,jupiter),
harmony(understanding,neptune),
craves(intoxication,cantelope),
locale(shrimp,moravia),
craves(anger,guava),
craves(curiosity,bacon),
craves(dread_2,cherry),
locale(cantelope,goias),
harmony(learning,neptune),
craves(achievement,beef),
locale(pepper,goias),
craves(love,wurst),
harmony(satiety,jupiter),
locale(wurst,oregon),
locale(cherry,surrey),
locale(pea,oregon),
craves(dread,bacon),
craves(hangover_4,hamburger),
locale(chicken,kentucky),
craves(triumph,popover),
craves(depression,pepper),
craves(rest,pea),
craves(abrasion,beef),
locale(marzipan,oregon),
locale(wonderbread,kentucky),
locale(ham,alsace),
craves(sciatica,wurst),
harmony(lubricity,mercury),
locale(hamburger,kentucky),
craves(lubricity,lamb),
locale(guava,surrey),
harmony(intoxication,mercury),
craves(boils,popover),
craves(learning,shrimp),
craves(abrasion_3,muffin),
harmony(achievement,neptune),
craves(anxiety,pea),
craves(satisfaction,pepper),
harmony(stimulation,neptune),
locale(bacon,oregon),
craves(hangover,ham),
craves(laceration,lamb),
locale(onion,alsace),
locale(popover,alsace),
harmony(entertainment,mercury),
craves(excitement,kale),
craves(angina,lettuce),
harmony(expectation,neptune),
locale(scallop,kentucky),
locale(muffin,surrey),
locale(lettuce,goias),
craves(understanding,ham),
harmony(rest,neptune),
craves(satiety,muffin),
craves(loneliness,scallop),
harmony(aesthetics,jupiter),
craves(sciatica_1,shrimp),
harmony(love,jupiter),
locale(lamb,kentucky),
craves(grief,marzipan),
craves(prostatitis,wonderbread),
craves(expectation,guava),
craves(jealousy,onion),
locale(kale,moravia),
craves(stimulation,lettuce),
locale(beef,alsace),
craves(aesthetics,scallop)]):-!.


goal([craves(hangover,lamb)]):-!.

goal1(List):-findall(X, not_determined(X), List).
not_determined(locale(City, Fuel)):-
    food(City),
    province(Fuel).
not_determined(craves(Car,City)):-
    pleasure(Car),
    food(City).
not_determined(harmony(Car, V)):-
    pleasure(Car),
    planet(V).
not_determined(craves(Cargo, City)):-
    pain(Cargo),
    Cargo\=hangover,
    food(City).
not_determined(fears(Cargo, Car)):-
    pain(Cargo),
    Cargo\=hangover,
    pleasure(Car).

