def(craves(Car,City)):-pleasure(Car), food(City).
def(craves(Cargo,City)):-pain(Cargo), food(City).
def(fears(Cargo, Car)):-pain(Cargo), pleasure(Car).
def(locale(City, Fuel)):-food(City),province(Fuel).
def(harmony(Car, V)):-pleasure(Car), planet(V).


food(guava).
food(chocolate).
food(wonderbread).
food(pepper).
food(cantelope).
food(tofu).
food(pea).
food(rice).
food(scallop).
food(hotdog).
food(lemon).
food(cucumber).
food(chicken).
food(haroset).
food(bacon).
food(potato).
food(orange).
food(marzipan).
food(broccoli).
food(wurst).
food(endive).
food(turkey).
pleasure(entertainment).
pleasure(learning).
pleasure(curiosity).
pleasure(rest).
pleasure(triumph).
pleasure(expectation).
pleasure(satisfaction).
pain(jealousy).
pain(prostatitis).
pain(depression).
pain(hangover).
pain(angina).
pain(anger).
pain(grief).
pain(boils).
pain(sciatica).
province(guanabara).
province(manitoba).
province(surrey).
province(alsace).
province(bosnia).
province(oregon).
province(moravia).
province(arizona).
planet(neptune).
planet(vulcan).
planet(pluto).
planet(jupiter).
attacks(guanabara,manitoba).
eats(wonderbread,guava).
orbits(vulcan,pluto).
eats(tofu,chocolate).
eats(pea,cucumber).
eats(scallop,lemon).
eats(hotdog,chicken).
orbits(pluto,jupiter).
eats(wonderbread,tofu).
eats(orange,marzipan).
eats(scallop,chicken).
eats(chocolate,cantelope).
eats(chocolate,tofu).
eats(pepper,cantelope).
eats(cantelope,pepper).
attacks(manitoba,surrey).
eats(rice,pea).
eats(lemon,scallop).
eats(wurst,potato).
eats(potato,scallop).
eats(lemon,cucumber).
eats(potato,turkey).
eats(cucumber,lemon).
eats(wonderbread,pea).
eats(guava,pepper).
eats(scallop,potato).
eats(hotdog,lemon).
attacks(bosnia,oregon).
eats(haroset,wurst).
eats(turkey,potato).
eats(bacon,wurst).
eats(cantelope,chocolate).
eats(hotdog,scallop).
eats(broccoli,turkey).
eats(cucumber,pea).
eats(chicken,rice).
eats(turkey,orange).
eats(pea,rice).
eats(pepper,guava).
attacks(alsace,bosnia).
eats(pea,wonderbread).
eats(wurst,haroset).
attacks(surrey,alsace).
eats(wurst,bacon).
eats(chicken,hotdog).
eats(rice,chicken).
eats(potato,wurst).
eats(haroset,endive).
eats(endive,haroset).
eats(marzipan,endive).
eats(bacon,broccoli).
eats(turkey,broccoli).
eats(endive,marzipan).
attacks(oregon,moravia).
eats(guava,wonderbread).
attacks(moravia,arizona).
eats(orange,turkey).
eats(marzipan,orange).
eats(chicken,scallop).
eats(broccoli,bacon).
orbits(neptune,vulcan).
eats(lemon,hotdog).
eats(scallop,hotdog).
eats(tofu,wonderbread).


initial([
harmony(rest,vulcan),
harmony(expectation,jupiter),
locale(cucumber,arizona),
locale(rice,moravia),
craves(entertainment,chocolate),
harmony(entertainment,jupiter),
locale(guava,bosnia),
craves(jealousy,wonderbread),
craves(anger,broccoli),
craves(triumph,bacon),
harmony(satisfaction,pluto),
craves(angina,marzipan),
locale(hotdog,guanabara),
craves(satisfaction,turkey),
locale(potato,manitoba),
locale(scallop,guanabara),
craves(prostatitis,scallop),
locale(chocolate,surrey),
locale(orange,guanabara),
craves(hangover,lemon),
locale(tofu,moravia),
locale(haroset,alsace),
locale(wonderbread,alsace),
locale(pea,surrey),
craves(learning,pepper),
craves(rest,scallop),

craves(boils,endive),
craves(depression,hotdog),
locale(endive,guanabara),
locale(cantelope,oregon),
locale(bacon,guanabara),
harmony(learning,vulcan),
craves(sciatica,turkey),
locale(turkey,surrey),
locale(lemon,bosnia),
craves(curiosity,cantelope),
craves(grief,wurst),
locale(marzipan,oregon),
harmony(curiosity,vulcan),
harmony(triumph,jupiter),
craves(expectation,potato),
locale(broccoli,surrey),
locale(pepper,oregon),
locale(chicken,manitoba),
locale(wurst,arizona)]):-!.

goal([craves(angina,chocolate)]):-!.

goal1(List):-findall(X, not_determined(X), List).
not_determined(locale(City, Fuel)):-
    food(City),
    province(Fuel).
not_determined(craves(Car,City)):-
    pleasure(Car),
    food(City).
not_determined(harmony(Car, V)):-
    pleasure(Car),
    planet(V).
not_determined(craves(Cargo, City)):-
    pain(Cargo),
    Cargo\=angina,
    food(City).
not_determined(fears(Cargo, Car)):-
    pain(Cargo),
    Cargo\=angina,
    pleasure(Car).

