(define (problem strips-mysty-x-13)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 city11 city12 city13 city14 city15 city16
             city17 city18 city19 city20 city21 city22 truck1
             truck2 truck3 truck4 truck5 truck6 truck7
             package1 package2 package3 package4 package5 package6 package7
             package8 package9 package10 package11 package12 package13 package14
             package15 package16 package17 package18 package19 package20
             package21 package22 package23 package24 package25
             package26 package27 package28 package29 package30
             package31 package32 package33 package34 package35
             package36 package37 package38 package39 package40
             package41 package42 package43 package44
             package45 package46     
               )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 fuel11 fuel12 fuel13 fuel14 fuel15 fuel16
             fuel17 fuel18 fuel19 fuel20 fuel21 fuel22 volume1
             volume2 volume3 volume4 volume5 volume6 volume7
                   
                   
                  
                 
                 
                 
                 
                
                   
               )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (city city16)
          (city_fuel city16 fuel16)
          (city city17)
          (city_fuel city17 fuel17)
          (city city18)
          (city_fuel city18 fuel18)
          (city city19)
          (city_fuel city19 fuel19)
          (city city20)
          (city_fuel city20 fuel20)
          (city city21)
          (city_fuel city21 fuel21)
          (city city22)
          (city_fuel city22 fuel22)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (package package16)
          (package package17)
          (package package18)
          (package package19)
          (package package20)
          (package package21)
          (package package22)
          (package package23)
          (package package24)
          (package package25)
          (package package26)
          (package package27)
          (package package28)
          (package package29)
          (package package30)
          (package package31)
          (package package32)
          (package package33)
          (package package34)
          (package package35)
          (package package36)
          (package package37)
          (package package38)
          (package package39)
          (package package40)
          (package package41)
          (package package42)
          (package package43)
          (package package44)
          (package package45)
          (package package46)
          (at package13 city7)
          (at package10 city7)
          (at package44 city22)
          (amount fuel14 1)
          (connected city21 city4)
          (at package17 city10)
          (at package31 city16)
          (connected city4 city21)
          (amount fuel12 0)
          (at package1 city3)
          (at truck3 city7)
          (connected city7 city1)
          (amount fuel4 0)
          (connected city21 city17)
          (connected city11 city10)
          (connected city15 city12)
          (connected city3 city4)
          (at truck4 city11)
          (connected city17 city21)
          (connected city20 city19)
          (amount fuel2 2)
          (at package23 city11)
          (connected city17 city22)
          (at package37 city18)
          (amount fuel17 2)
          (connected city19 city20)
          (connected city5 city11)
          (connected city4 city3)
          (amount fuel6 1)
          (at package32 city17)
          (at package14 city9)
          (at package33 city17)
          (at package18 city10)
          (amount volume6 3)
          (connected city16 city18)
          (at package35 city18)
          (at truck2 city6)
          (at package38 city18)
          (amount fuel22 3)
          (at package6 city5)
          (connected city19 city18)
          (amount fuel9 2)
          (amount fuel5 0)
          (connected city8 city15)
          (connected city11 city13)
          (amount volume5 2)
          (at package36 city18)
          (connected city14 city8)
          (connected city16 city22)
          (amount volume3 1)
          (at truck1 city3)
          (at package5 city5)
          (connected city10 city9)
          (at package34 city17)
          (connected city1 city7)
          (connected city11 city5)
          (connected city1 city2)
          (at package4 city5)
          (at truck7 city19)
          (connected city22 city13)
          (connected city6 city5)
          (connected city22 city16)
          (connected city2 city1)
          (amount fuel13 1)
          (connected city13 city22)
          (connected city8 city14)
          (at truck6 city17)
          (amount volume2 2)
          (amount fuel16 3)
          (at truck5 city12)
          (amount fuel15 2)
          (at package27 city12)
          (at package20 city10)
          (connected city3 city5)
          (at package3 city5)
          (amount fuel11 2)
          (connected city7 city4)
          (at package29 city14)
          (at package12 city7)
          (at package25 city11)
          (connected city18 city16)
          (amount fuel10 1)
          (amount volume4 3)
          (at package2 city4)
          (at package28 city12)
          (amount fuel21 1)
          (connected city9 city12)
          (at package39 city18)
          (at package42 city19)
          (at package9 city7)
          (at package8 city6)
          (connected city5 city6)
          (amount fuel7 3)
          (connected city20 city21)
          (at package46 city22)
          (at package19 city10)
          (at package26 city12)
          (at package41 city19)
          (at package7 city6)
          (amount fuel3 3)
          (at package22 city11)
          (connected city6 city2)
          (at package11 city7)
          (connected city12 city9)
          (connected city5 city3)
          (amount fuel1 1)
          (connected city13 city14)
          (connected city12 city15)
          (connected city2 city6)
          (connected city15 city8)
          (connected city10 city11)
          (amount fuel18 1)
          (at package24 city11)
          (at package16 city9)
          (amount volume1 3)
          (at package45 city22)
          (amount fuel20 2)
          (connected city14 city13)
          (at package40 city19)
          (connected city13 city11)
          (connected city9 city10)
          (amount fuel19 2)
          (at package21 city11)
          (connected city21 city20)
          (connected city4 city7)
          (amount fuel8 0)
          (at package43 city22)
          (amount volume7 1)
          (at package15 city9)
          (connected city18 city19)
          (at package30 city14)
          (connected city22 city17))
   (:goal (and (at package44 city21)
               (at package46 city12))))
