(define (problem strips-mysty-x-9)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             truck1 truck2 truck3 truck4 package1 package2
             package3 package4 package5 package6 package7 package8
             package9 package10 package11 package12 package13   
                  )
   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             volume1 volume2 volume3 volume4  
                  )

(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)

          (connected city1 city7)
          (connected city7 city1)
          (connected city4 city3)
          (connected city2 city4)
          (connected city4 city2)
          (connected city3 city7)
          (connected city6 city5)
          (connected city7 city3)
          (connected city6 city1)
          (connected city2 city5)
          (connected city1 city6)
          (connected city5 city2)
          (connected city5 city6)
          (connected city3 city4)

          (amount fuel1 2)
          (amount fuel2 2)
          (amount fuel3 2)
          (amount fuel4 0)
          (amount fuel5 1)
          (amount fuel6 1)
          (amount fuel7 4)

          (amount volume1 3)
          (amount volume2 1)
          (amount volume3 1)
          (amount volume4 1)

          (at package1 city2)
          (at package2 city2)
          (at package3 city3)
          (at package4 city3)
          (at package5 city3)
          (at package6 city3)
          (at package7 city3)
          (at package8 city5)
          (at package9 city5)
          (at package10 city7)
          (at package11 city7)
          (at package12 city7)
          (at package13 city7)


          (at truck2 city3)
          (at truck3 city6)
          (at truck1 city2)
          (at truck4 city7)
)
   (:goal (and (at package2 city4)
               (at package11 city5))))