(define (problem strips-mysty-x-17)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7 city8
             city9 city10 city11 city12 city13 city14 city15 city16
             truck1 truck2 truck3 truck4 truck5 truck6
             truck7 truck8 truck9 package1 package2 package3 package4
             package5 package6 package7 package8 package9 package10 package11
             package12 package13 package14 package15 package16 package17
             package18 package19 package20   
                   )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7 fuel8
             fuel9 fuel10 fuel11 fuel12 fuel13 fuel14 fuel15 fuel16
             volume1 volume2 volume3 volume4 volume5 volume6
             volume7 volume8 volume9    
                   
                  
                  
                   )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (city city16)
          (city_fuel city16 fuel16)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (truck truck8)
          (truck_volume truck8 volume8)
          (truck truck9)
          (truck_volume truck9 volume9)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (package package16)
          (package package17)
          (package package18)
          (package package19)
          (package package20)
          (at package11 city9)
          (amount fuel10 4)
          (at package7 city5)
          (amount fuel6 3)
          (amount fuel14 5)
          (connected city1 city4)
          (connected city7 city6)
          (amount fuel1 4)
          (amount volume6 1)
          (connected city13 city16)
          (connected city2 city5)
          (at truck7 city10)
          (connected city8 city15)
          (at package16 city14)
          (at package8 city6)
          (connected city15 city8)
          (at package1 city1)
          (connected city1 city5)
          (connected city11 city6)
          (connected city5 city1)
          (connected city4 city1)
          (connected city7 city10)
          (amount fuel9 5)
          (amount fuel11 4)
          (connected city6 city7)
          (connected city11 city15)
          (connected city9 city4)
          (at package15 city11)
          (connected city7 city14)
          (amount volume9 1)
          (at truck8 city14)
          (connected city9 city3)
          (connected city2 city3)
          (at package5 city3)
          (connected city9 city16)
          (connected city15 city12)
          (connected city9 city8)
          (amount fuel7 3)
          (connected city10 city7)
          (at package10 city8)
          (connected city10 city8)
          (amount fuel12 2)
          (amount fuel15 2)
          (at truck4 city4)
          (connected city3 city4)
          (amount volume7 3)
          (connected city4 city3)
          (at package3 city2)
          (amount fuel8 4)
          (at package4 city2)
          (connected city12 city15)
          (connected city5 city2)
          (at truck6 city7)
          (amount volume5 3)
          (connected city15 city11)
          (connected city6 city11)
          (at package18 city15)
          (connected city3 city9)
          (amount fuel5 0)
          (amount fuel3 4)
          (amount volume1 3)
          (amount volume2 2)
          (amount fuel2 4)
          (connected city9 city12)
          (at package17 city15)
          (at package14 city11)
          (at truck2 city2)
          (connected city16 city13)
          (amount volume4 3)
          (amount volume8 3)
          (connected city14 city7)
          (amount fuel16 2)
          (connected city10 city13)
          (connected city16 city9)
          (at truck3 city3)
          (connected city4 city9)
          (at truck5 city5)
          (connected city11 city14)
          (connected city13 city10)
          (amount fuel13 1)
          (amount volume3 1)
          (at package9 city7)
          (at package12 city9)
          (at truck1 city1)
          (connected city8 city10)
          (connected city14 city11)
          (at package20 city16)
          (at package13 city10)
          (at truck9 city15)
          (amount fuel4 4)
          (connected city8 city9)
          (at package19 city16)
          (connected city3 city2)
          (at package6 city4)
          (connected city12 city9)
          (at package2 city1))
   (:goal (and (at package8 city11))))
