(define (problem strips-mysty-x-24)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 city11 city12 city13 city14 city15
             truck1 truck2 truck3 package1 package2 package3 package4
             package5 package6 package7 package8 package9 package10 package11
             package12 package13 package14 package15 package16 package17
             package18 package19 package20 package21 package22 package23
             package24 package25 package26 package27 package28
             package29 package30 package31 package32 package33
             package34 package35 package36 package37  
                    
                )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 fuel11 fuel12 fuel13 fuel14 fuel15
             volume1 volume2 volume3    
                   
                  
                  
                 
                 
                  
                    
                )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (package package16)
          (package package17)
          (package package18)
          (package package19)
          (package package20)
          (package package21)
          (package package22)
          (package package23)
          (package package24)
          (package package25)
          (package package26)
          (package package27)
          (package package28)
          (package package29)
          (package package30)
          (package package31)
          (package package32)
          (package package33)
          (package package34)
          (package package35)
          (package package36)
          (package package37)
          (amount volume2 2)
          (at package30 city13)
          (connected city14 city13)
          (at truck3 city7)
          (at package34 city15)
          (at package23 city10)
          (connected city4 city5)
          (connected city15 city14)
          (connected city7 city3)
          (connected city1 city5)
          (amount fuel10 1)
          (connected city11 city10)
          (connected city2 city6)
          (amount fuel3 0)
          (amount volume3 3)
          (connected city10 city12)
          (at truck2 city5)
          (amount fuel4 4)
          (connected city9 city14)
          (at package10 city6)
          (connected city13 city14)
          (at package14 city7)
          (connected city12 city10)
          (at package37 city15)
          (connected city8 city12)
          (connected city2 city3)
          (at package13 city6)
          (at package8 city4)
          (connected city3 city7)
          (amount volume1 2)
          (at package16 city9)
          (at package1 city1)
          (amount fuel8 4)
          (amount fuel6 2)
          (at package9 city4)
          (amount fuel12 0)
          (at package27 city12)
          (at truck1 city2)
          (at package3 city2)
          (at package35 city15)
          (connected city14 city9)
          (amount fuel7 3)
          (connected city12 city8)
          (at package6 city4)
          (at package21 city10)
          (at package7 city4)
          (at package18 city9)
          (connected city13 city11)
          (connected city1 city6)
          (at package2 city1)
          (connected city3 city6)
          (connected city7 city15)
          (amount fuel13 1)
          (connected city14 city15)
          (connected city8 city9)
          (connected city2 city4)
          (amount fuel14 9)
          (connected city9 city15)
          (connected city15 city9)
          (amount fuel11 3)
          (at package28 city12)
          (connected city6 city3)
          (connected city11 city13)
          (connected city7 city12)
          (at package11 city6)
          (amount fuel15 9)
          (connected city10 city11)
          (amount fuel5 5)
          (connected city15 city7)
          (connected city12 city7)
          (at package31 city13)
          (at package26 city11)
          (connected city6 city1)
          (at package5 city3)
          (at package32 city14)
          (at package36 city15)
          (at package17 city9)
          (amount fuel1 2)
          (amount fuel9 9)
          (at package24 city11)
          (at package15 city8)
          (at package4 city3)
          (at package25 city11)
          (connected city9 city8)
          (connected city4 city2)
          (connected city5 city4)
          (amount fuel2 0)
          (at package22 city10)
          (at package29 city13)
          (at package20 city10)
          (at package33 city15)
          (connected city5 city1)
          (at package12 city6)
          (connected city3 city2)
          (connected city6 city2)
          (at package19 city9))
   (:goal (and (at package16 city9)
               (at package18 city9)
               (at package28 city2))))
