(define (problem strips-mysty-x-14)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 city11 city12 city13 city14 city15
             city16 city17 city18 city19 city20 city21 truck1 truck2
             truck3 truck4 truck5 truck6 truck7 truck8
             truck9 package1 package2 package3 package4 package5 package6
             package7 package8 package9 package10 package11 package12 package13
             package14 package15 package16 package17 package18 package19
             package20 package21 package22 package23 package24 package25
             package26 package27 package28 package29 package30
             package31 package32 package33 package34 package35
             package36 package37 package38 package39 package40
             package41 package42 package43 package44  
                    )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 fuel11 fuel12 fuel13 fuel14 fuel15
             fuel16 fuel17 fuel18 fuel19 fuel20 fuel21 volume1 volume2
             volume3 volume4 volume5 volume6 volume7 volume8
             volume9      
                   
                  
                  
                 
                 
                 
                  
                    )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (city city16)
          (city_fuel city16 fuel16)
          (city city17)
          (city_fuel city17 fuel17)
          (city city18)
          (city_fuel city18 fuel18)
          (city city19)
          (city_fuel city19 fuel19)
          (city city20)
          (city_fuel city20 fuel20)
          (city city21)
          (city_fuel city21 fuel21)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (truck truck8)
          (truck_volume truck8 volume8)
          (truck truck9)
          (truck_volume truck9 volume9)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (package package16)
          (package package17)
          (package package18)
          (package package19)
          (package package20)
          (package package21)
          (package package22)
          (package package23)
          (package package24)
          (package package25)
          (package package26)
          (package package27)
          (package package28)
          (package package29)
          (package package30)
          (package package31)
          (package package32)
          (package package33)
          (package package34)
          (package package35)
          (package package36)
          (package package37)
          (package package38)
          (package package39)
          (package package40)
          (package package41)
          (package package42)
          (package package43)
          (package package44)
          (amount volume8 2)
          (amount volume6 2)
          (at package22 city11)
          (amount fuel11 3)
          (at package20 city10)
          (connected city8 city9)
          (amount fuel14 1)
          (connected city1 city5)
          (amount fuel15 5)
          (connected city17 city21)
          (amount volume3 3)
          (connected city5 city1)
          (at truck9 city21)
          (at package8 city4)
          (connected city12 city10)
          (at package16 city8)
          (connected city13 city14)
          (at package14 city8)
          (at package19 city10)
          (amount fuel13 3)
          (connected city5 city3)
          (connected city2 city7)
          (amount fuel6 5)
          (amount fuel4 2)
          (connected city10 city11)
          (at package34 city16)
          (connected city9 city11)
          (connected city13 city9)
          (amount fuel3 5)
          (amount fuel2 2)
          (amount volume7 3)
          (connected city16 city19)
          (at package17 city9)
          (at truck7 city18)
          (at package1 city1)
          (at truck6 city15)
          (connected city20 city21)
          (at package27 city12)
          (at package12 city7)
          (connected city11 city9)
          (at package11 city5)
          (connected city8 city10)
          (at package13 city8)
          (at package39 city19)
          (connected city14 city11)
          (at package36 city18)
          (connected city19 city16)
          (at truck1 city1)
          (at package42 city21)
          (amount fuel7 1)
          (connected city11 city4)
          (amount volume4 2)
          (at package24 city11)
          (connected city15 city16)
          (at package4 city2)
          (connected city4 city1)
          (at package37 city18)
          (connected city17 city15)
          (at package7 city3)
          (at package30 city13)
          (connected city16 city20)
          (connected city6 city2)
          (connected city9 city15)
          (connected city18 city21)
          (at truck8 city20)
          (amount fuel12 2)
          (at package23 city11)
          (connected city9 city13)
          (at package5 city3)
          (at package18 city9)
          (connected city15 city6)
          (at truck2 city2)
          (connected city4 city7)
          (connected city15 city17)
          (connected city10 city8)
          (connected city10 city12)
          (amount volume1 1)
          (amount fuel20 0)
          (connected city11 city10)
          (at package26 city12)
          (at package15 city8)
          (connected city9 city8)
          (amount fuel10 3)
          (at package25 city12)
          (at package21 city10)
          (at package6 city3)
          (amount fuel8 1)
          (at package29 city13)
          (at package3 city2)
          (at package10 city4)
          (connected city20 city19)
          (connected city17 city18)
          (connected city20 city16)
          (connected city15 city9)
          (amount fuel17 2)
          (at package43 city21)
          (amount fuel5 5)
          (connected city20 city17)
          (at package33 city16)
          (at package2 city2)
          (connected city12 city9)
          (amount fuel21 2)
          (connected city7 city4)
          (amount volume2 2)
          (amount fuel1 4)
          (connected city16 city15)
          (at package28 city13)
          (connected city17 city20)
          (at package32 city16)
          (connected city3 city6)
          (connected city4 city11)
          (at package44 city21)
          (connected city6 city15)
          (amount fuel16 2)
          (connected city18 city17)
          (connected city11 city14)
          (at truck5 city10)
          (connected city6 city3)
          (amount fuel18 5)
          (connected city9 city12)
          (connected city21 city20)
          (connected city1 city4)
          (amount volume9 3)
          (amount volume5 3)
          (connected city21 city18)
          (at package40 city19)
          (connected city3 city5)
          (connected city7 city2)
          (at package31 city13)
          (amount fuel19 1)
          (at truck4 city4)
          (connected city2 city6)
          (at package9 city4)
          (at package38 city19)
          (at package35 city16)
          (connected city14 city13)
          (connected city19 city20)
          (connected city21 city17)
          (at truck3 city3)
          (amount fuel9 3)
          (at package41 city20))
   (:goal (and (at package38 city4)
               (at package40 city4))))
