(define (problem strips-mysty-x-30)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 city11 city12 city13 truck1
             truck2 truck3 truck4 truck5 package1 package2
             package3 package4 package5 package6 package7   
                   
                   )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 fuel11 fuel12 fuel13 volume1
             volume2 volume3 volume4 volume5  
                    
                   
                   )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)

          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)

          (amount fuel3 6)
          (amount fuel9 10)
          (at package1 city2)
          (at truck2 city4)
          (amount fuel5 8)
          (at package6 city10)
          (at truck4 city10)
          (at package4 city8)
          (amount volume4 3)
          (amount volume1 1)
          (amount fuel13 8)
          (amount fuel6 12)
          (at truck1 city1)
          (amount fuel8 3)
          (at truck5 city13)
          (amount fuel1 4)
          (amount volume3 3)
          (amount fuel10 9)
          (at package2 city3)
          (amount volume5 1)
          (at package7 city13)
          (at truck3 city9)
          (amount volume2 3)
          (amount fuel2 10)
          (amount fuel4 10)
          (amount fuel7 1)
          (amount fuel11 8)
          (amount fuel12 6)
          (at package3 city5)
          (at package5 city9)

          (connected city6 city2)
          (connected city5 city3)
          (connected city3 city5)
          (connected city12 city11)
          (connected city13 city10)
          (connected city1 city8)
          (connected city1 city5)
          (connected city4 city9)
          (connected city3 city12)
          (connected city9 city6)
          (connected city7 city8)
          (connected city7 city6)
          (connected city8 city6)
          (connected city13 city12)
          (connected city6 city9)
          (connected city5 city1)
          (connected city2 city6)
          (connected city12 city3)
          (connected city4 city3)
          (connected city1 city2)
          (connected city3 city4)
          (connected city11 city10)
          (connected city9 city4)
          (connected city4 city6)
          (connected city2 city3)
          (connected city8 city7)
          (connected city3 city2)
          (connected city11 city12)
          (connected city8 city1)
          (connected city12 city13)
          (connected city2 city1)
          (connected city6 city4)
          (connected city10 city13)
          (connected city6 city8)
          (connected city10 city11)
          (connected city6 city7)

)
   (:goal (and (at package2 city7)
               (at package5 city7)
               (at package4 city8))))
