(define (problem strips-mysty-x-22)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 city11 city12 city13 city14 city15 city16
             city17 city18 city19 city20 city21 truck1 truck2
             truck3 truck4 truck5 truck6
             truck7 truck8 truck9 truck10 truck11 truck12
             truck13 truck14 truck15 truck16 package1 package2 package3
             package4 package5 package6 package7 package8 package9 package10
             package11 package12 package13 package14 package15 package16
             package17 package18      
                )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 fuel11 fuel12 fuel13 fuel14 fuel15 fuel16
             fuel17 fuel18 fuel19 fuel20 fuel21 volume1 volume2
             volume3 volume4 volume5 volume6
             volume7 volume8 volume9 volume10 volume11 volume12
             volume13 volume14 volume15 volume16   
                   
                  
                    
                )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (city city16)
          (city_fuel city16 fuel16)
          (city city17)
          (city_fuel city17 fuel17)
          (city city18)
          (city_fuel city18 fuel18)
          (city city19)
          (city_fuel city19 fuel19)
          (city city20)
          (city_fuel city20 fuel20)
          (city city21)
          (city_fuel city21 fuel21)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (truck truck8)
          (truck_volume truck8 volume8)
          (truck truck9)
          (truck_volume truck9 volume9)
          (truck truck10)
          (truck_volume truck10 volume10)
          (truck truck11)
          (truck_volume truck11 volume11)
          (truck truck12)
          (truck_volume truck12 volume12)
          (truck truck13)
          (truck_volume truck13 volume13)
          (truck truck14)
          (truck_volume truck14 volume14)
          (truck truck15)
          (truck_volume truck15 volume15)
          (truck truck16)
          (truck_volume truck16 volume16)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (package package16)
          (package package17)
          (package package18)
          (amount volume8 1)
          (at truck6 city9)
          (amount volume15 1)
          (connected city14 city16)
          (amount volume2 2)
          (amount volume3 2)
          (connected city13 city18)
          (amount volume4 1)
          (connected city19 city17)
          (connected city8 city7)
          (connected city21 city16)
          (at truck7 city10)
          (connected city2 city3)
          (connected city13 city17)
          (connected city16 city15)
          (connected city15 city18)
          (amount fuel18 4)
          (connected city12 city13)
          (connected city12 city10)
          (connected city17 city12)
          (at package8 city8)
          (connected city15 city10)
          (at truck2 city5)
          (at package15 city17)
          (amount fuel10 3)
          (connected city7 city8)
          (connected city8 city9)
          (connected city4 city5)
          (connected city2 city1)
          (amount volume14 1)
          (connected city3 city1)
          (at truck10 city13)
          (connected city17 city13)
          (amount fuel11 3)
          (connected city15 city11)
          (connected city6 city5)
          (connected city5 city4)
          (at truck11 city14)
          (connected city17 city19)
          (connected city11 city14)
          (amount volume16 2)
          (connected city18 city21)
          (amount fuel14 5)
          (amount fuel17 0)
          (amount fuel16 5)
          (connected city18 city15)
          (at package5 city5)
          (at package17 city19)
          (amount fuel9 2)
          (connected city16 city21)
          (at truck3 city6)
          (at package9 city11)
          (at truck13 city16)
          (at package11 city13)
          (connected city19 city20)
          (connected city20 city14)
          (amount fuel2 5)
          (amount fuel3 2)
          (connected city13 city12)
          (connected city5 city2)
          (amount fuel7 1)
          (connected city20 city12)
          (at package12 city14)
          (amount volume12 3)
          (amount fuel19 2)
          (connected city16 city14)
          (connected city11 city15)
          (connected city3 city2)
          (connected city1 city2)
          (connected city6 city7)
          (connected city12 city19)
          (connected city12 city18)
          (at truck12 city15)
          (amount fuel8 0)
          (amount volume7 3)
          (connected city20 city11)
          (at package6 city6)
          (at truck14 city18)
          (at package18 city21)
          (connected city9 city6)
          (connected city15 city16)
          (connected city18 city13)
          (amount volume10 1)
          (connected city19 city12)
          (at package14 city16)
          (connected city12 city20)
          (connected city11 city20)
          (at truck8 city11)
          (amount volume1 1)
          (connected city7 city6)
          (amount fuel5 5)
          (connected city1 city3)
          (connected city14 city20)
          (at package7 city7)
          (connected city14 city11)
          (connected city2 city5)
          (at package13 city15)
          (connected city10 city12)
          (connected city21 city18)
          (amount fuel4 1)
          (amount fuel6 1)
          (amount volume6 3)
          (at truck15 city20)
          (at package1 city1)
          (amount volume5 1)
          (connected city9 city17)
          (amount fuel12 2)
          (amount fuel21 0)
          (amount fuel1 3)
          (at truck4 city7)
          (amount volume13 1)
          (at truck16 city21)
          (connected city4 city1)
          (at package10 city12)
          (amount volume9 2)
          (connected city9 city8)
          (at package16 city18)
          (amount volume11 2)
          (connected city10 city15)
          (amount fuel15 2)
          (at package2 city2)
          (connected city5 city6)
          (connected city1 city4)
          (connected city12 city17)
          (connected city6 city9)
          (connected city20 city19)
          (at package3 city3)
          (at truck5 city8)
          (connected city18 city12)
          (at package4 city4)
          (amount fuel20 4)
          (connected city17 city9)
          (at truck1 city1)
          (amount fuel13 1)
          (at truck9 city12))
   (:goal (and (at package7 city15))))
