(define (problem strips-mysty-x-7)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 truck1 truck2 package1 package2
             package3 package4 package5 package6 package7 package8 package9
             package10 package11 package12 package13 package14 package15
             package16 package17 package18 package19 package20 package21
             package22 package23 package24   
               )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 volume1 volume2  
                   
                  
                  
                  
               )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (package package16)
          (package package17)
          (package package18)
          (package package19)
          (package package20)
          (package package21)
          (package package22)
          (package package23)
          (package package24)
          (at package19 city8)
          (amount fuel8 0)
          (connected city1 city8)
          (connected city6 city7)
          (at package24 city10)
          (at package3 city1)
          (at package11 city5)
          (connected city1 city7)
          (amount fuel7 2)
          (connected city8 city3)
          (connected city7 city1)
          (amount volume1 1)
          (at package16 city7)
          (amount fuel3 1)
          (at package17 city7)
          (connected city3 city9)
          (amount fuel4 2)
          (connected city5 city4)
          (at package7 city4)
          (at truck2 city7)
          (at package5 city2)
          (connected city9 city2)
          (connected city4 city5)
          (connected city4 city6)
          (at truck1 city5)
          (connected city6 city10)
          (at package13 city6)
          (connected city6 city4)
          (at package20 city9)
          (at package10 city5)
          (at package21 city9)
          (at package22 city9)
          (amount fuel5 0)
          (connected city4 city2)
          (connected city7 city6)
          (connected city7 city5)
          (at package6 city3)
          (connected city8 city9)
          (at package14 city6)
          (amount fuel2 0)
          (at package18 city7)
          (amount fuel6 1)
          (connected city10 city9)
          (connected city9 city8)
          (connected city3 city8)
          (at package1 city1)
          (connected city3 city5)
          (amount fuel1 0)
          (connected city9 city10)
          (at package4 city2)
          (connected city9 city3)
          (at package15 city7)
          (connected city5 city3)
          (at package9 city5)
          (connected city5 city7)
          (connected city2 city9)
          (at package12 city5)
          (at package23 city9)
          (amount fuel9 3)
          (amount volume2 1)
          (connected city10 city6)
          (connected city2 city4)
          (at package2 city1)
          (amount fuel10 0)
          (connected city8 city1)
          (at package8 city4))
   (:goal (and (at package6 city8))))
