(define (problem strips-mysty-x-27)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7 truck1
             truck2 truck3 package1 package2 package3 package4 package5
             package6     
                    
                )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7 volume1
             volume2 volume3     
                  
                    
                )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (amount fuel1 10)
          (at package1 city1)
          (connected city1 city2)
          (connected city4 city3)
          (connected city7 city3)
          (amount fuel5 12)
          (at package2 city1)
          (connected city7 city6)
          (at package6 city7)
          (amount volume3 2)
          (connected city3 city7)
          (amount fuel7 5)
          (connected city5 city1)
          (connected city7 city2)
          (connected city3 city4)
          (at truck1 city5)
          (connected city1 city5)
          (at package3 city1)
          (amount volume2 2)
          (amount fuel6 9)
          (amount volume1 3)
          (amount fuel2 9)
          (amount fuel3 2)
          (connected city3 city5)
          (at truck3 city7)
          (connected city6 city5)
          (connected city5 city3)
          (connected city6 city7)
          (connected city2 city7)
          (connected city5 city4)
          (connected city2 city1)
          (connected city5 city6)
          (connected city4 city5)
          (at truck2 city6)
          (at package4 city7)
          (amount fuel4 5)
          (at package5 city7)
          )
   (:goal (and (at package5 city2)
               (at package6 city2))))
