(define (problem strips-mysty-x-12)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7 city8
             truck1 truck2 truck3 truck4 package1 package2 package3 
                    
             )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7 fuel8
             volume1 volume2 volume3 volume4    
                    
             )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (package package1)
          (package package2)
          (package package3)
          (connected city3 city8)
          (amount fuel7 6)
          (amount fuel6 1)
          (amount fuel3 4)
          (connected city5 city4)
          (at package1 city5)
          (connected city7 city1)
          (amount volume4 1)
          (at truck1 city1)
          (amount volume2 1)
          (connected city1 city7)
          (connected city8 city7)
          (connected city2 city1)
          (at truck3 city5)
          (connected city6 city7)
          (connected city5 city3)
          (at package3 city8)
          (connected city4 city6)
          (connected city3 city7)
          (amount volume3 1)
          (at package2 city5)
          (at truck4 city8)
          (amount fuel1 2)
          (connected city3 city5)
          (amount fuel2 3)
          (connected city4 city5)
          (amount fuel4 1)
          (at truck2 city3)
          (connected city7 city3)
          (connected city1 city2)
          (connected city6 city4)
          (connected city7 city8)
          (amount volume1 2)
          (connected city2 city5)
          (connected city8 city3)
          (amount fuel5 1)
          (amount fuel8 0)
          (connected city7 city6)
          (connected city5 city2)
          )
   (:goal (and (at package3 city4))))
