(define (problem strips-mysty-x-5)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 truck1 truck2 truck3 truck4
             package1 package2 package3 package4 package5 package6 package7
             package8 package9 package10 package11 package12 package13 package14
             package15        )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 volume1 volume2 volume3 volume4
                   
                   
                     )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (package package14)
          (package package15)
          (connected city8 city7)
          (at truck1 city1)
          (amount volume2 3)
          (at package9 city6)
          (connected city4 city1)
          (connected city5 city8)
          (at package3 city1)
          (at truck3 city4)
          (connected city7 city6)
          (connected city6 city5)
          (amount fuel4 3)
          (connected city7 city8)
          (at package15 city8)
          (amount volume4 2)
          (at truck2 city3)
          (at package14 city8)
          (connected city1 city2)
          (at package5 city3)
          (connected city4 city3)
          (connected city2 city6)
          (at truck4 city5)
          (amount fuel7 1)
          (connected city3 city2)
          (connected city6 city7)
          (at package13 city8)
          (at package12 city8)
          (at package8 city6)
          (amount volume1 2)
          (connected city2 city3)
          (connected city2 city1)
          (at package10 city6)
          (at package2 city1)
          (amount fuel8 0)
          (at package7 city3)
          (at package4 city1)
          (amount fuel6 1)
          (connected city5 city6)
          (amount fuel3 1)
          (amount fuel1 3)
          (connected city1 city4)
          (at package6 city3)
          (amount fuel2 2)
          (connected city8 city5)
          (amount volume3 2)
          (connected city6 city2)
          (at package11 city7)
          (amount fuel5 0)
          (at package1 city1)
          (connected city3 city4))
   (:goal (and (at package14 city6)
               (at package3 city6))))
