(define (problem strips-mysty-x-15)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7 city8
             city9 city10 city11 city12 city13 city14 city15 city16 city17
             truck1 truck2 truck3 truck4 truck5
             truck6 truck7 truck8 truck9 truck10 truck11
             package1 package2 package3 package4 package5 package6 package7
             package8 package9 package10 package11 package12 package13  
                   
                  )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7 fuel8
             fuel9 fuel10 fuel11 fuel12 fuel13 fuel14 fuel15 fuel16 fuel17
             volume1 volume2 volume3 volume4 volume5
             volume6 volume7 volume8 volume9 volume10 volume11
                   
                    
                   
                  )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (city city16)
          (city_fuel city16 fuel16)
          (city city17)
          (city_fuel city17 fuel17)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (truck truck8)
          (truck_volume truck8 volume8)
          (truck truck9)
          (truck_volume truck9 volume9)
          (truck truck10)
          (truck_volume truck10 volume10)
          (truck truck11)
          (truck_volume truck11 volume11)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (package package10)
          (package package11)
          (package package12)
          (package package13)
          (connected city14 city17)
          (at truck4 city7)
          (at truck8 city14)
          (at package6 city7)
          (amount volume2 3)
          (at package7 city7)
          (at package11 city12)
          (connected city12 city13)
          (connected city15 city16)
          (connected city8 city4)
          (at truck3 city4)
          (amount fuel12 4)
          (amount fuel15 3)
          (at truck11 city17)
          (at truck1 city1)
          (amount fuel10 5)
          (connected city1 city3)
          (connected city11 city12)
          (at truck7 city11)
          (at package1 city1)
          (at package5 city5)
          (connected city4 city8)
          (connected city7 city9)
          (at package4 city5)
          (connected city17 city14)
          (amount volume4 2)
          (connected city17 city13)
          (at truck2 city2)
          (connected city9 city7)
          (connected city6 city1)
          (connected city4 city2)
          (amount fuel6 4)
          (connected city12 city11)
          (at package8 city9)
          (amount volume11 1)
          (connected city5 city2)
          (amount volume10 3)
          (connected city10 city13)
          (amount volume3 1)
          (connected city5 city6)
          (amount volume9 3)
          (connected city3 city1)
          (connected city6 city2)
          (connected city16 city15)
          (amount volume8 3)
          (connected city2 city4)
          (amount fuel16 2)
          (at truck9 city15)
          (amount fuel7 3)
          (amount fuel9 3)
          (amount fuel4 10)
          (connected city3 city4)
          (amount fuel3 4)
          (connected city2 city6)
          (connected city6 city5)
          (amount fuel13 6)
          (connected city14 city8)
          (amount fuel2 6)
          (connected city10 city16)
          (amount fuel14 3)
          (at package3 city3)
          (connected city7 city8)
          (amount volume1 1)
          (amount fuel11 2)
          (connected city8 city14)
          (connected city14 city11)
          (at truck10 city16)
          (at truck6 city10)
          (connected city11 city14)
          (connected city5 city4)
          (connected city1 city6)
          (at truck5 city9)
          (connected city13 city10)
          (connected city9 city15)
          (connected city15 city9)
          (amount fuel8 5)
          (amount fuel5 7)
          (connected city4 city5)
          (at package10 city12)
          (at package2 city3)
          (amount fuel1 1)
          (amount fuel17 1)
          (connected city13 city12)
          (connected city16 city10)
          (amount volume6 2)
          (at package12 city16)
          (connected city4 city3)
          (at package9 city10)
          (connected city13 city17)
          (amount volume5 3)
          (connected city2 city5)
          (connected city8 city7)
          (at package13 city17)
          (amount volume7 1))
   (:goal (and (at package8 city5))))
