(define (problem strips-mysty-x-16)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 city9 city10 city11 truck1 truck2 truck3
             truck4 truck5 truck6 truck7 package1 package2
             package3 package4 package5 package6 package7 package8 package9
                   
               )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 fuel9 fuel10 fuel11 volume1 volume2 volume3
             volume4 volume5 volume6 volume7  
                   
                   
               )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (package package9)
          (connected city8 city7)
          (amount fuel7 1)
          (amount volume2 3)
          (amount volume5 2)
          (amount fuel9 0)
          (connected city1 city5)
          (amount volume4 1)
          (at truck3 city6)
          (at package5 city8)
          (amount fuel5 4)
          (at truck1 city1)
          (at truck7 city11)
          (connected city6 city9)
          (connected city11 city7)
          (connected city2 city11)
          (at package4 city5)
          (amount fuel1 0)
          (connected city6 city8)
          (amount fuel10 1)
          (amount fuel11 5)
          (at truck5 city9)
          (connected city3 city9)
          (connected city9 city6)
          (at truck2 city2)
          (at package8 city9)
          (at package2 city2)
          (amount fuel3 4)
          (amount fuel4 0)
          (at package9 city9)
          (connected city2 city3)
          (connected city8 city6)
          (connected city5 city1)
          (connected city10 city5)
          (at package1 city1)
          (connected city1 city4)
          (connected city11 city4)
          (at package6 city8)
          (connected city4 city1)
          (at package3 city5)
          (connected city10 city9)
          (connected city7 city11)
          (amount volume6 2)
          (at truck4 city8)
          (at package7 city9)
          (amount volume1 1)
          (connected city3 city2)
          (amount volume3 3)
          (connected city9 city3)
          (connected city11 city2)
          (connected city7 city8)
          (amount fuel6 3)
          (at truck6 city10)
          (connected city4 city11)
          (connected city5 city10)
          (connected city9 city10)
          (amount volume7 2)
          (amount fuel8 2)
          (amount fuel2 3))
   (:goal (and (at package7 city10)
               (at package8 city10))))
