(define (problem strips-mysty-x-11)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7
             city8 truck1 package1 package2 package3 package4
             package5 package6 package7 package8    
                 )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7
             fuel8 volume1    
                    
                 )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (truck truck1)
          (truck_volume truck1 volume1)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (package package6)
          (package package7)
          (package package8)
          (at package5 city5)
          (connected city3 city7)
          (connected city2 city1)
          (amount fuel5 4)
          (connected city1 city6)
          (amount fuel4 1)
          (connected city4 city3)
          (amount fuel3 2)
          (amount fuel2 0)
          (connected city8 city6)
          (connected city7 city3)
          (connected city4 city8)
          (connected city1 city2)
          (at truck1 city3)
          (connected city6 city1)
          (amount fuel8 2)
          (connected city8 city5)
          (connected city2 city3)
          (connected city3 city4)
          (at package2 city2)
          (connected city5 city6)
          (at package1 city1)
          (connected city6 city8)
          (at package8 city8)
          (connected city8 city4)
          (amount fuel6 5)
          (at package6 city6)
          (at package3 city3)
          (amount fuel7 3)
          (connected city5 city8)
          (connected city3 city2)
          (connected city7 city6)
          (at package4 city4)
          (connected city6 city7)
          (at package7 city7)
          (connected city6 city5)
          (amount fuel1 3)
          (amount volume1 2))
   (:goal (and (at package3 city5)
               (at package4 city5))))
