(define (problem strips-mysty-x-8)
   (:domain mystery-strips)
   (:objects city1 city2 city3 city4 city5 city6 city7 city8 city9
             city10 city11 city12 city13 city14 city15 city16
             city17 city18 truck1 truck2 truck3 truck4
             truck5 truck6 truck7 truck8 truck9 package1
             package2 package3 package4 package5   
                  )

   
(:resources fuel1 fuel2 fuel3 fuel4 fuel5 fuel6 fuel7 fuel8 fuel9
             fuel10 fuel11 fuel12 fuel13 fuel14 fuel15 fuel16
             fuel17 fuel18 volume1 volume2 volume3 volume4
             volume5 volume6 volume7 volume8 volume9 
                   
                  )


(:init (city city1)
          (city_fuel city1 fuel1)
          (city city2)
          (city_fuel city2 fuel2)
          (city city3)
          (city_fuel city3 fuel3)
          (city city4)
          (city_fuel city4 fuel4)
          (city city5)
          (city_fuel city5 fuel5)
          (city city6)
          (city_fuel city6 fuel6)
          (city city7)
          (city_fuel city7 fuel7)
          (city city8)
          (city_fuel city8 fuel8)
          (city city9)
          (city_fuel city9 fuel9)
          (city city10)
          (city_fuel city10 fuel10)
          (city city11)
          (city_fuel city11 fuel11)
          (city city12)
          (city_fuel city12 fuel12)
          (city city13)
          (city_fuel city13 fuel13)
          (city city14)
          (city_fuel city14 fuel14)
          (city city15)
          (city_fuel city15 fuel15)
          (city city16)
          (city_fuel city16 fuel16)
          (city city17)
          (city_fuel city17 fuel17)
          (city city18)
          (city_fuel city18 fuel18)
          (truck truck1)
          (truck_volume truck1 volume1)
          (truck truck2)
          (truck_volume truck2 volume2)
          (truck truck3)
          (truck_volume truck3 volume3)
          (truck truck4)
          (truck_volume truck4 volume4)
          (truck truck5)
          (truck_volume truck5 volume5)
          (truck truck6)
          (truck_volume truck6 volume6)
          (truck truck7)
          (truck_volume truck7 volume7)
          (truck truck8)
          (truck_volume truck8 volume8)
          (truck truck9)
          (truck_volume truck9 volume9)
          (package package1)
          (package package2)
          (package package3)
          (package package4)
          (package package5)
          (amount volume5 2)
          (connected city9 city10)
          (connected city5 city6)
          (connected city14 city12)
          (amount volume4 1)
          (connected city12 city16)
          (at truck9 city17)
          (connected city6 city5)
          (connected city18 city11)
          (amount volume1 2)
          (amount volume7 3)
          (amount fuel7 3)
          (at package2 city5)
          (connected city1 city4)
          (amount fuel14 1)
          (connected city8 city11)
          (connected city7 city15)
          (at truck6 city11)
          (connected city2 city3)
          (amount fuel6 4)
          (at package1 city2)
          (at package3 city5)
          (connected city14 city15)
          (amount fuel16 2)
          (connected city6 city1)
          (amount fuel9 1)
          (at truck2 city2)
          (connected city2 city12)
          (amount fuel4 1)
          (connected city11 city18)
          (connected city1 city6)
          (at package4 city10)
          (connected city10 city9)
          (connected city17 city16)
          (connected city6 city2)
          (amount fuel17 3)
          (connected city16 city17)
          (amount fuel13 1)
          (connected city3 city2)
          (at truck3 city3)
          (connected city3 city4)
          (amount fuel8 2)
          (connected city5 city1)
          (at truck5 city8)
          (at package5 city10)
          (connected city5 city4)
          (at truck7 city12)
          (amount fuel3 0)
          (connected city12 city14)
          (connected city12 city2)
          (connected city4 city1)
          (amount volume2 3)
          (at truck1 city1)
          (connected city10 city17)
          (amount volume8 2)
          (amount fuel1 0)
          (connected city17 city10)
          (connected city4 city5)
          (connected city4 city3)
          (amount fuel12 1)
          (connected city11 city8)
          (amount fuel18 2)
          (connected city1 city5)
          (connected city16 city12)
          (connected city18 city13)
          (connected city15 city7)
          (connected city15 city14)
          (connected city13 city9)
          (amount fuel15 1)
          (connected city7 city8)
          (amount fuel10 3)
          (amount volume9 3)
          (amount fuel2 3)
          (amount volume3 2)
          (connected city2 city6)
          (connected city8 city7)
          (connected city9 city13)
          (amount volume6 1)
          (amount fuel5 0)
          (at truck8 city16)
          (at truck4 city5)
          (connected city13 city18)
          (amount fuel11 0))
   (:goal (and (at package3 city12))))
